# Generated by Django 4.0.3 on 2022-03-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_conta_tipo_conta_text_conta_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='email_text',
            field=models.CharField(default='dtc@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conta',
            name='localidade_text',
            field=models.CharField(default='ULisbon', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conta',
            name='nr_telemovel_text',
            field=models.CharField(default='917560028', max_length=11),
            preserve_default=False,
        ),
    ]
