# Generated by Django 4.0.3 on 2022-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_conta_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='money_text',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conta',
            name='nr_conta_text',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conta',
            name='nr_telemovel_text',
            field=models.IntegerField(),
        ),
    ]
