# Generated by Django 4.0.3 on 2022-03-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_conta_money_text_alter_conta_nr_conta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='name_text',
            field=models.CharField(default='rogerio', max_length=200),
            preserve_default=False,
        ),
    ]
